FROM nixos/nix:latest AS deps
ENV PATH="/nix/var/nix/profiles/default/bin:$PATH" \
    INSIDE_DOCKER="true"
COPY . /app
WORKDIR /app
RUN nix                                                   \
    --extra-experimental-features "nix-command flakes"    \
    --option filter-syscalls false                        \
    build
