version: '3.8'

services:
  db:
    image: mysql:latest
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  api:
    image: recipes-api:latest
    #build: 
    #  context: .
    environment:
      ORM_URL: mysql+pymysql://user:password@db/mydatabase
    platform: linux/amd64
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  db_data:
