# fly.toml app configuration file generated for recipes-rfs on 2024-06-27T09:33:21+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'recipes-rfs'
primary_region = 'nrt'

[build]
  image = 'ghcr.io/rodfersou/recipes-api:latest'

[env]
  ORM_URL = 'mysql+pymysql://user:password@mysql-rfs.internal/mydatabase'

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
