"""Initial migration

Revision ID: dd58db09bce7
Revises: 
Create Date: 2024-06-25 17:13:25.792710

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'dd58db09bce7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    recipe_table = op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('making_time', sa.String(length=100), nullable=False),
    sa.Column('serves', sa.String(length=100), nullable=False),
    sa.Column('ingredients', sa.String(length=300), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    
    op.bulk_insert(
        recipe_table,
        [
            {
                "id": 1,
                "title": 'Chicken Curry',
                "making_time": '45 min',
                "serves": '4 people',
                "ingredients": 'onion, chicken, seasoning',
                "cost": 1000,
                "created_at": '2016-01-10 12:10:12',
                "updated_at": '2016-01-10 12:10:12',
            },
            {
                "id": 2,
                "title": 'Rice Omelette',
                "making_time": '30 min',
                "serves": '2 people',
                "ingredients": 'onion, egg, seasoning, soy sauce',
                "cost": 700,
                "created_at": '2016-01-11 13:10:12',
                "updated_at": '2016-01-11 13:10:12',
            },
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe')
    # ### end Alembic commands ###
