# fly.toml app configuration file generated for mysql-rfs on 2024-06-27T10:03:22+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mysql-rfs'
primary_region = 'nrt'

[build]
  image = 'mysql:latest'

[env]
  MYSQL_DATABASE = 'mydatabase'
  MYSQL_USER = 'user'

[processes]
  app = '--datadir /data/mysql --mysql-native-password=ON'

[[mounts]]
  source = 'mysqldata'
  destination = '/data'

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
