app = 'mysql-rfs'
primary_region = 'nrt'

[build]
  image = 'mysql:8'

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1

[processes]
  app = """--datadir /data/mysql \
    --default-authentication-plugin mysql_native_password"""

[mounts]
  source = "mysqldata"
  destination = "/data"

[env]
  MYSQL_DATABASE = "mydatabase"
  MYSQL_USER = "user"
