#!/bin/bash
cd -P "$(dirname "$0")/.."

echo $PAT | docker login ghcr.io -u rodfersou --password-stdin
docker buildx build --progress plain --platform linux/amd64 -t recipes-api .
docker tag recipes-api:latest ghcr.io/rodfersou/recipes-api:latest
docker push ghcr.io/rodfersou/recipes-api:latest
